version: '3.8'
services:
  postgres-test:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123456*
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata17:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
volumes:
  pgdata17:
